fonts <- c("Agency FB", "Albany AMT", "ALGERIAN", "Andale Sans for VST", "Aparajita", "Arial", "Arial Rounded MT Bold", "Arial Unicode MS", "Arno Pro", "Baskerville Old Face",
"Bauhaus 93","Bell Gothic Std Light", "Bell MT", "Berlin Sans FB", "Berlin Sans FB Demi Bold", "Bernard MT Condensed", "Birch Std", "Blackadder ITC", "Blackoak Std","Bodoni MT",
"Book Antiqua","Bradley Hand ITC","Britannic Bold", "Broadway", "Brush Script MT Italic", "Brush Script Std", "Calibri", "Californian FB","Calisto MT", "Cambria",
"Candara", "Adobe Caslon Pro", "CASTELLAR", "Centaur", "Century", "Century Gothic", "Century Schoolbook", "Chaparral Pro", "Charlemagne Std", "Chiller", "Colonna MT",
"Comic Sans MS", "Copperplate Gothic Bold", "Monotype Corsiva", "Courier New", "Cumberland AMT", "Curlz MT", "David", "DaunPenh", "Adobe Devanagari", "Ebrima", "Eccentric Std",
"Elephant", "Engravers MT", "Estrangelo Edessa", "Euclid", "Euclid Fraktur", "Euphemia", "Dotum", "Felix Titling", "Forte", "Franklin Gothic Medium Cont", "Freestyle Script",
"French Script MT", "Garamond", "Giddyup Std", "GOUDY STOUT", "Harrington", "Haettenschweiler", "Harlow solid Italic", "Hobo Std", "Impact", "Imprint", "Jokerman", "Juice MC", "KaiTi", "Kokila",
"Imprint MT Shadow", "Informal Roman", "Lucida Console", "Lucida Sans Unicode","Magneto","Mistral","MS Gothic", "MV Boli", "Narkisim", "Niagara Engraved", "Nueva Std","Old English Text MT", "Palatino Linotype",
"Rosewood Std Regular", "SAS Monospace", "Stencil", "Tahoma", "Times New Roman", "Times New Roman Symbol", "Trajan Pro","Verdana", "Viner Hand ITC")

windowsFonts(f1 =  windowsFont(fonts[1]),  f2 = windowsFont(fonts[2]),
f3 = windowsFont(fonts[3]), f4 = windowsFont(fonts[4]), f5= windowsFont(fonts[5]),
f6 = windowsFont(fonts[6]), f7 = windowsFont(fonts[7]), f8 = windowsFont(fonts[8]),
f9 = windowsFont(fonts[9]), f10 = windowsFont(fonts[10]), f11 = windowsFont(fonts[11]),
f12 = windowsFont(fonts[12]), f13 = windowsFont(fonts[13]), f14 = windowsFont(fonts[14]),
f15 = windowsFont(fonts[15]), f16 = windowsFont(fonts[16]), f17 = windowsFont(fonts[17]),
f18 = windowsFont(fonts[18]), f19 = windowsFont(fonts[19]), f20 = windowsFont(fonts[20]),
f21 = windowsFont(fonts[21]), f22 = windowsFont(fonts[22]), f23 = windowsFont(fonts[23]),
f24 = windowsFont(fonts[24]), f25 = windowsFont(fonts[25]), f26 = windowsFont(fonts[26]),
f27 = windowsFont(fonts[27]), f28 = windowsFont(fonts[28]), f29 = windowsFont(fonts[29]),
f30 = windowsFont(fonts[30]), f31 = windowsFont(fonts[31]), f32 = windowsFont(fonts[32]),
f33 = windowsFont(fonts[33]), f34 = windowsFont(fonts[34]), f35 = windowsFont(fonts[35]),
f36 = windowsFont(fonts[36]), f37 = windowsFont(fonts[37]), f38 = windowsFont(fonts[38]),
f39 = windowsFont(fonts[39]), f40 = windowsFont(fonts[40]), f41 = windowsFont(fonts[41]),
f42 = windowsFont(fonts[42]), f43 = windowsFont(fonts[43]), f44 = windowsFont(fonts[44]),
f45 = windowsFont(fonts[45]), f46 = windowsFont(fonts[46]), f47 = windowsFont(fonts[47]),
f48 = windowsFont(fonts[48]), f49 = windowsFont(fonts[49]), f50 = windowsFont(fonts[50]),
f51 = windowsFont(fonts[51]), f52 = windowsFont(fonts[52]), f53 = windowsFont(fonts[53]),
f54 = windowsFont(fonts[54]), f55 = windowsFont(fonts[55]), f56 = windowsFont(fonts[56]),
f57 = windowsFont(fonts[57]), f58 = windowsFont(fonts[58]), f59 = windowsFont(fonts[59]),
f60 = windowsFont(fonts[60]), f61 = windowsFont(fonts[61]), f62 = windowsFont(fonts[62]),
f63 = windowsFont(fonts[63]), f64 = windowsFont(fonts[64]), f65 = windowsFont(fonts[65]),
f64 = windowsFont(fonts[64]), f65 = windowsFont(fonts[65]), f66 = windowsFont(fonts[66]),
f67 = windowsFont(fonts[67]), f68 = windowsFont(fonts[68]), f69 = windowsFont(fonts[69]),
f70 = windowsFont(fonts[70]), f71 = windowsFont(fonts[71]), f72 = windowsFont(fonts[72]),
f73 = windowsFont(fonts[73]), f74 = windowsFont(fonts[74]), f75 = windowsFont(fonts[75]),
f76 = windowsFont(fonts[76]), f77 = windowsFont(fonts[77]), f78 = windowsFont(fonts[78]),
f79 = windowsFont(fonts[79]), f80 = windowsFont(fonts[80]), f81 = windowsFont(fonts[81]),
f82 = windowsFont(fonts[82]), f83 = windowsFont(fonts[83]), f84 = windowsFont(fonts[84]),
f85 = windowsFont(fonts[85]), f86 = windowsFont(fonts[86]), f87 = windowsFont(fonts[87]),
f88 = windowsFont(fonts[88]), f89 = windowsFont(fonts[89]), f90 = windowsFont(fonts[90]),
f91 = windowsFont(fonts[91]), f92 = windowsFont(fonts[92]), f93 = windowsFont(fonts[93]),
f94 = windowsFont(fonts[94]), f95 = windowsFont(fonts[95]), f96 = windowsFont(fonts[96]),
f97 = windowsFont(fonts[97]), f98 = windowsFont(fonts[98]), f99 = windowsFont(fonts[99]))